# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Path.ls_sorted": "01_utils.ipynb",
         "flatten_dict": "01_utils.ipynb",
         "most_common": "01_utils.ipynb",
         "get_node": "01_utils.ipynb",
         "apply_nested": "01_utils.ipynb",
         "resolve_path": "01_utils.ipynb",
         "set_dir": "01_utils.ipynb",
         "generate_time_id": "01_utils.ipynb",
         "parse_distortion_severity": "02_wrangling.ipynb",
         "parse_scene": "02_wrangling.ipynb",
         "label_dataframe": "02_wrangling.ipynb",
         "make_dataframe_splitter": "02_wrangling.ipynb",
         "populate_frames": "02_wrangling.ipynb",
         "make_framer": "02_wrangling.ipynb",
         "remove_corrupt_video_frames": "02_wrangling.ipynb",
         "make_dataframe": "02_wrangling.ipynb",
         "make_train_dataframe": "02_wrangling.ipynb",
         "assert_stratied_split": "02_wrangling.ipynb",
         "make_test_dataframe": "02_wrangling.ipynb",
         "ImageTuple": "03_datablock.ipynb",
         "ImageTupleBlock": "03_datablock.ipynb",
         "CombinedLoss": "04_loss.ipynb",
         "LearnerProxy": "05_metric.ipynb",
         "route_to_metric": "05_metric.ipynb",
         "BaselineSTM": "06_model.ipynb",
         "BaselineMTM": "06_model.ipynb",
         "MultiScaleBackbone": "06_model.ipynb",
         "MultiScaleMTM": "06_model.ipynb",
         "SequenceSTM": "06_model.ipynb",
         "SequenceMTM": "06_model.ipynb",
         "evaluate_mtl": "07_evaluation.ipynb",
         "evaluate_stl": "07_evaluation.ipynb",
         "decode_preds": "08_inference.ipynb",
         "fill_preds": "08_inference.ipynb",
         "aggregate_preds": "08_inference.ipynb",
         "format_pred": "08_inference.ipynb",
         "get_test_inferences": "08_inference.ipynb",
         "make_submission": "08_inference.ipynb",
         "most_freq": "08_inference.ipynb",
         "log_training_dataset": "09_experiment.ipynb",
         "log_model_evaluation": "09_experiment.ipynb",
         "log_predictions": "09_experiment.ipynb"}

modules = ["utils.py",
           "wrangling.py",
           "datablock.py",
           "loss.py",
           "metric.py",
           "model.py",
           "evaluation.py",
           "inference.py",
           "experiment.py"]

doc_url = "https://bdsaglam.github.io/vqa/"

git_url = "https://github.com/bdsaglam/icip-vqa/tree/master/"

def custom_doc_links(name): return None
