# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/10_inference_stl.ipynb (unless otherwise specified).

__all__ = ['get_test_inferences', 'make_submission_preds']

# Cell

import numpy as np
from fastai.basics import *
from .utils import most_common

# Cell

def get_test_inferences(dls, learn, tst_df):
    tst_dl = dls.test_dl(tst_df)
    tst_learn = Learner(
        dls,
        learn.model,
        loss_func=learn.loss_func,
        splitter=learn.model.splitter
    )
    probs, targets, preds = tst_learn.get_preds(dl=tst_dl, with_decoded=True)

    inference_df = tst_df.copy()
    inference_df['preds'] = np.array(dls.vocab)[preds.cpu().numpy()]
    inference_df = inference_df.groupby(by='video_name').agg({
        'label': first,
        'preds': list,
    })
    inference_df['pred'] = inference_df['preds'].apply(most_common)
    return inference_df

def make_submission_preds(preds):
    return [','.join(sorted(ds[1:] for ds in pred.split(','))) for pred in preds]
